version: "3"
services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pass2020!
      - POSTGRES_DB=course
  api_server:
    image: quarkus/course-registration-jvm
    ports:
      - 8080:8080
    restart: always