version: "3"
services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ${HOME}/postgres-data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Pass2020
  api_server:
    image: quarkus/course-registration-jvm
    ports:
      - 8080:8080
    restart: always