version: "3"
services:
  database:
    image: quarkus/course-registration-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pass2020!
      - POSTGRES_DB=course
  server:
    image: quarkus/course-registration-jvm
    ports:
      - 8080:8080
    restart: always